apiVersion: apps/v1
kind:  Deployment
metadata: 
  name: siddhesh
  labels:
    app: deployapp
spec:
    strategy:
      type: RollingUpdate
      rollingUpdate:
            maxSurge: 1     
            maxUnavailable: 1  
    selector:
      matchLabels: 
          app: deployapp
    replicas: 5
    template:
      metadata:
        labels:
          name: nginxapp
          app: deployapp
      spec:
        containers:
          - name: nginxapp
            image: httpd:latest 
            ports:
                - containerPort: 80
                  protocol: TCP
                  
---
apiVersion: v1
kind: Service
metadata: 
  name: nodeportservice
spec:
  type: Nodeport
  selector:
    app: deployapp
  ports:
   - ports: 80
     targetport: 80
     name: nginx
     protocol: TCP     
                  
