apiVersion: apps/v1
kind:  Deployment
metadata: 
  name: sideploy
  labels:
    app: deployapp
spec:
    strategy:
      type: RollingUpdate
      rollingUpdate:
            maxSurge: 1    
            maxUnavailable: 1  
    selector: 
      matchLabels: 
          app: deployapp
    replicas: 8
    template:
      metadata:
        labels:
          name: httpdapp
          app: deployapp
      spec:
        containers:
          - name: httpdapplication
            image: httpd:latest 
            ports:
                - containerPort: 80
                  protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: NodePort
  selector:
    app: deployapp
  ports:
    - port: 80
      targetPort: 80
      name: nginx
      protocol: TCP
