apiVersion: apps/v1
kind:  Deployment
metadata: 
  name: siddeploy
  labels:
    app: siddapp
spec:
    strategy:
      type: RollingUpdate
      rollingUpdate:
            maxSurge: 1     
    selector: 
      matchLabels: 
          app: siddapp
    replicas: 8
    template:
      metadata:
        labels:
          name: httpdapp
          app: siddapp
      spec:
        containers:
          - name: httpdapplication
            image: httpd:latest 
            ports:
                - containerPort: 80
                  protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  type: NodePort
  selector:
    app: siddapp
  ports:
    - port: 80
      targetPort: 80
      name: nginx
      protocol: TCP
