apiVersion: apps/v1
kind:  Deployment
metadata: 
  name: siddhesh
  labels:
    app: deployapp
spec:
    strategy:
      type: RollingUpdate
      rollingUpdate:
            maxSurge: 1     
            maxUnavailable: 1  
    selector:
      matchLabels: 
          app: deployapp
    replicas: 10
    template:
      metadata:
        labels:
          name: nginxapp
          app: deployapp
      spec:
        containers:
          - name: nginxapp
            image: httpd:latest 
            ports:
                - containerPort: 80
                  protocol: TCP
                  
