apiVersion: v1
kind: Pod 
metadata: 
  name: dharma
  namespace: siddhesh
  labels:   
    app: sdapp 
spec: 
    containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort : 80
              protocol : TCP
              name: nginx
--- 
apiVersion: v1 
kind: Service
metadata:
    name: dharmaservice
    namespace: siddhesh 
spec: 
    type: NodePort
    selector: 
      app: sdapp
    ports: 
        - port: 80 
          targetPort: 80
          protocol: TCP 
    
