apiVersion: apps/v1
kind:  ReplicaSet
metadata: 
  name: siddhesh
  labels:
    app: myapp
spec:
    selector: 
      matchExpressions:      
         -  { key: app, operator: In , values: [myapp,  new-app]}  
    #matchLabels: 
          #app: myapp
    replicas: 2
    template:
      metadata:
        labels:
          name: nginxapp
          app: myapp
      spec:
        containers:
          - name: nginxapp
            image: nginx:latest 
            ports:
                - containerPort: 80
                  protocol: TCP
