apiVersion: v1
kind: Pod
metadata:
  name: dharma-app
  labels:
    apps: new-app
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
      protocol: TCP
  - name: tomcat
    image: tomcat:latest
    ports:
    - containerPort: 8080
      prptocol: TCP   