apiversion: v1
kind: Service
metadata:
  name: nodeportsrc
spec:
    ports:
    - port: 80
      targetport: 80
      name: nginx
      protocol: TCP

    - port: 8080
      targetport: 8080
      name: tomcat
      protocol: TCP
